version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: distributter-app
    volumes:
      - './bin:/app/bin'
      - './src:/app/src'
      - './vendor:/app/vendor'
      - './storage.v3.json:/app/storage.v3.json'
      - './docker/app/session.madeline.docker:/app/session.madeline.docker'
      - './shared:/app/shared'
      - './logs:/app/logs'
    tmpfs:
      - '/tmp'
      - '/var/tmp'
    restart: unless-stopped

  tts:
    build:
      context: .
      dockerfile: docker/tts/Dockerfile
    container_name: distributter-tts
    volumes:
      - './shared:/app/shared'
      - './tts_models:/root/.local/share/tts'
    restart: "no"
    profiles:
      - tts

volumes:
  shared:
