version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: distributter-app
    volumes:
      - ./storage.v3.json:/app/storage.v3.json
      - ./session.madeline:/app/session.madeline
      - ./shared:/app/shared
    restart: unless-stopped

  tts:
    build:
      context: .
      dockerfile: docker/tts/Dockerfile
    container_name: distributter-tts
    volumes:
      - ./shared:/app/shared
      - ./tts_models:/root/.local/share/tts
    restart: unless-stopped

volumes:
  shared:
